### PR TITLE
Add function to link switch to router

### PR DESCRIPTION
**Pull request by jxiaobin**
The function accepts switch name, switch port name, router name, router port
name, router port mac, network and etc, then does following:
1. create router port
2. create switch port
3. add router port to router
4. add switch port to switch

so that the switch will be connected to router.

### CODE REVIEW

**Comment by vtolstov** [comment]
i'm really need to complete own pr to be able to create free form rows in ovnnb tables

**Comment by jxiaobin** [comment]
If the operation is split into multiple calls, client needs to handle rollback stuff. The purpose of this function is to make the operation transactional, so we don’t have to handle failures in the middle.

**Comment by vtolstov** [comment]
thanks, can we run transaction before changes, add changes and commit transaction?

**Comment by jxiaobin** [comment]
sorry, I didn't get your point, do you mean wrap the transaction in something like begin, operations, then commit blocks like sql?

**Comment by vtolstov** [comment]
yes, as i know ovsdb have transactions support, so may be best way to write code that uses transactions and avoid duplicate logic inside go-ovn functions?

**Comment by hzhou8** [comment]
@vtolstov I agree with you but the feature of combining APIs calls in a single transaction is not ready yet in go-ovn/libovsdb. See https://github.com/eBay/go-ovn/issues/18

So I'd say let's go ahead with @jxiaobin 's approach for now, until we have the complete transaction support ready. What do you think?

**Comment by vtolstov** [comment]
@hzhou8 yes, i'm agree with you.

**Pull request merged**
