### PR TITLE
fix goreportcard issues

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
@lebauce may the current travis tests failed because of some changes to deleting items in cache?
(i'm try to fix some issues founded with goreportcard and found this)

**Comment by lebauce** [comment]
@vtolstov strange. I'm checking

**Comment by lebauce** [comment]
@vtolstov It seems the `cmd, err = ovndbapi.ACLAdd(LSW, "to-lport", MATCH, "drop", 1001, nil, true, "")` is done twice in acl_test.go Therefore, the check you added to the second one will fail, the test will exit leaving the logical switch it created, making the following tests fail too. We should probably use `defer` to delete the objects created during the test.

**Comment by lebauce** [comment]
@vtolstov exactly

**Pull request merged**
