### PR TITLE
minor fixes for internal api

### PR DESCRIPTION
**Pull request by vtolstov**
* provide all table names, also prefix table names with table
* name all operations with op
* split ovnnbimp.go to smaller parts

Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
this is trivial improvement and fix

**Comment by vtolstov** [comment]
i'm complete spliting code to files

**Comment by hzhou8** [comment]
This doesn't look like "minor", but it is really great refactoring. Thanks for the great work 👍

**Comment by vtolstov** [comment]
thanks =) I look forward to reviewing..

**Comment by softwarejl** [comment]
LGTM

**Pull request merged**
