### PR TITLE
Extend port group API to support:

### PR DESCRIPTION
**Pull request by anfredette**
- PortGroupAddPort() - Add a port to a port group
- PortGroupRemovePort() - Remove a port from a port group

Signed-off-by: Andre Fredette <afredette@redhat.com>

### CODE REVIEW

**Review by vtolstov — APPROVED** [review]
LGTM

**Comment by vtolstov** [comment]
@hzhou8 @anfredette what you think about moving from travis-ci to github actions for tests ?

**Comment by vtolstov** [comment]
mostly trivial changes to add new methods without breaking changes, i'm merge it @hzhou8

**Comment by anfredette** [comment]
Thanks, Vasiliy.

Andre

**Pull request merged**
