### PR TITLE
show lb , ports ,sr in LRGet

### PR DESCRIPTION
**Pull request by JackyCZJ**
Find it can't show any LoadBlancer , ports, staticRouter information in LRGet ,try to add it.

### CODE REVIEW

**Comment by vtolstov** [comment]
can you add test to such options? For example attach LoadBalancer to LogicalRouter and after that get LogicalRouter and check that LoadBalancer column contains needed data?

**Comment by JackyCZJ** [comment]
, I just recived right data form my option, I will add some test tomorrow . Sorry for poor English.

**Comment by vtolstov** [comment]
thanks, i think that you do something wrong. new commits not goes to this pr.
Can you fix it?

**Comment by JackyCZJ** [comment]
Yes , actually I did something wrong so I reset it , I will fix it at tomorrow cuz  I can't code nomally right now, Sorry for border you.

**Comment by vtolstov** [comment]
thanks!

**Pull request merged**
