### PR TITLE
Fix unit tests as error handling commit missed to address it

### PR DESCRIPTION
**Pull request by noah8713**

### CODE REVIEW

**Comment by vtolstov** [comment]
i think that this can be fixed by https://github.com/eBay/go-ovn/pull/31

**Comment by noah8713** [comment]
@vtolstov Thanks for pointer. Better to use separate commit for this fix. Each merge should not break the functionality. Lets merge this and then you can rebase on top of this.

**Comment by vtolstov** [comment]
main problem that this example not tested by script, may be add go build -o /dev/null this file in tests?

**Comment by vtolstov** [comment]
so if something breaks in api we can known?

**Comment by noah8713** [comment]
Yeah sure in the travis ci script. We can also add to test examples.go. However, lets use a separate commit for that too

**Comment by vtolstov** [comment]
i think that pr #31 that have commits for each stuff is fine (yes it lack test for examples)

**Comment by vtolstov** [comment]
and also nobody restrict to revert one of commits later if that needed

**Pull request merged**
