### PR TITLE
WIP: test rewrite

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by hzhou8** [comment]
Hi @vtolstov, this looks promising but you didn't update it for a while. Could you share your plan on this? Thanks!

**Comment by vtolstov** [comment]
Hi and sorry, busy at other tasks. I'm plan to complete this in this week.

**Comment by vtolstov** [comment]
@hzhou8 @lebauce can you look at acl.go in this pr.
I think that it looks better with some reflection based stuff in ovnnbimp.go. Also for listing we don't need reconstruct item each time and save allocations.
But i don't like getRows in ovnnbimp.go (i think that it can looks simpler then now)

**Comment by vtolstov** [comment]
@hzhou8 may be i found the solution.
goovn store all data in cache with map[string]interface{}
when user wants some struct - convert from map to native struct
when user wants to add some object (acl, qos, logical switch...) he don't provide map, but use something like this
```
type Options map[string]interface{}
ACLAdd(target string, opts ...ACLOpt) cmd, error
ACLOpt is the type Option func(Options)

for example for ACLAdd options is like:
func Direction(d string) Option {
  return func(o Options) {
    o["direction"] = d
  }
}

func Priority(p int) Option {
  return func(o Options) {
    o["priority"] = p
  }
}

func Match(m string) Option {
  return func(o Options) {
    o["match"] = m
  }
}

func Action(a string) Option {
  return func(o Options) {
    o["action"] = a
  }
}
```

**Comment by vtolstov** [comment]
so we always know what params we need to pass, and have ability to validate it.
to check existence of item we can iterate over map (this is simpler when my previous reflection based stuff)

**Comment by vtolstov** [comment]
abandon

**Pull request closed without merging**
